#!/bin/bash
# tests/test_commit_message.sh — commit-msg hook 정책 테스트
source "$(dirname "$0")/test_helper.sh"

HOOK="$REPO_ROOT/.githooks/commit-msg"

run_hook() {
  local message="$1"
  local msg_file
  msg_file="$(make_tmpdir)/COMMIT_EDITMSG"
  printf '%s\n' "$message" > "$msg_file"
  "$HOOK" "$msg_file" >/tmp/ai-setting-commit-hook.out 2>&1
  return $?
}

suite "한글 커밋 제목 허용"
run_hook "문서: Homebrew 배포 경로 정리"
assert_exit_code 0 "$?" "한글 제목 통과"

suite "영문 전용 제목 차단"
run_hook "docs: update homebrew guide"
assert_exit_code 1 "$?" "영문 제목 차단"

suite "짧은 바디 요약 허용"
run_hook "배포: Homebrew 자동화 점검"$'\n\n'"- workflow_dispatch 성공"$'\n'"- tap diff 없음 확인"
assert_exit_code 0 "$?" "짧은 바디 통과"

suite "과도한 바디 차단"
run_hook "배포: Homebrew 자동화 점검"$'\n\n'"- 첫째"$'\n'"- 둘째"$'\n'"- 셋째"$'\n'"- 넷째"
assert_exit_code 1 "$?" "4줄 바디 차단"

suite "AI 출처 문구 차단"
run_hook "문서: 배포 메모 정리"$'\n\n'"Generated by Claude"
assert_exit_code 1 "$?" "AI 출처 문구 차단"

print_summary
